-- // insert default products
-- Migration SQL that makes the change goes here.

INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (1, 'Radeema', 'RA', 8, 1, 'radeema.png', 'P_radeema.bmp', NULL, 1, '1', 0, '080 2000 123', 1, 1, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (2, 'Bayn', 'BA', 1, 1, 'bayn.png', 'p_bayn.bmp', '1- Compose le 111&#xD;&#xA;2- Ecoute le message qui t&#8217;invite &#224;&#xD;&#xA;saisir le code de recharge&#xD;&#xA;3- Saisis le code de recharge&#xD;&#xA;4- Valide par la touche "#"&#xD;&#xA;5- Un SMS te sera envoy&#233; pour confirmer&#xD;&#xA;la recharge.', 4, '1', 0, '05 29 000 220', 1, 3, 'comment recharger? 555....', '97C43D');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (3, 'INWI', 'IN', 1, 1, 'inwi.png', 'p_inwi.bmp', '1- Composez *120*20*suvi du code de&#xD;&#xA;recharge puis #&#xD;&#xA;2- Confirmez avec la touche appel.', 2, '1', 0, '05 29 000 220', 1, 2, 'comment recharger? 555....', '92278F');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (5, 'WANA-HDM', 'WH', 2, 1, 'wanahdm.png', 'p_wanahdm.bmp', '1.Composez le 110 depuis un t&#233;l&#233;phone&#xD;&#xA;inwi ou le 05 20000 110 depuis une autre&#xD;&#xA;ligne et suivez les instructions vocales&#xD;&#xA;2.Saisissez le num&#233;ro de votre ligne&#xD;&#xA;internet et validez par #&#xD;&#xA;3.Saisissez le Pin code et validez par #&#xD;&#xA;Vous pouvez &#233;galement recharger via&#xD;&#xA;www.inwi.ma', 1, '1', 0, '05 29 000 220', 1, 1, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (7, 'Redal', 'RE', 8, 1, 'redal.png', 'P_redal.bmp', NULL, 2, '1', null, '05 37 20 20 80', 1, 2, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (8, 'Radeel', 'RD', 8, 1, 'radeel.png', 'P_radeel.bmp', NULL, 1, '1', 0, '067 49 08 768', 0, 1, NULL, '00489A');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (9, 'Maroc Telecom', 'MT', 1, 1, 'maroctelecom.png', 'p_maroctelecom.bmp', 'Introduisez les 14 chiffres de la recharge en appelant le 555 ou en envoyant un SMS au 555', 1, '1', 0, '0801000888', 1, 1, NULL, '00489A');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (10, 'Ramsa', 'RA', 8, 1, 'ramsa.png', 'p_ramsa.bmp', NULL, 3, '1', 0, '0528 22 30 30', 1, 3, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (11, 'Amendis', 'AM', 8, 1, 'amendis.png', 'p_amendis.bmp', NULL, 4, '1', 0, '0802008000', 1, 4, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (12, 'TeleFlouss', 'TF', 5, 1, 'teleflouss.png', 'p_teleflouss.bmp', NULL, 1, '1', 0, '06 60 60 60', 1, 1, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (13, 'CashPago', 'CP', 6, 1, 'cashpago.png', 'p_cashpago.bmp', 'nothing', 1, '1', 0, 'support@cashpago.com', 1, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (14, 'SuperCode', 'SC', 6, 1, 'supercode.png', 'p_supercode.bmp', 'nothing', 1, '1', 0, 'support@supercode.ma', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (15, 'MPOST PASSPORT', 'MPDR', 6, 1, 'mpostpassport.png', 'p_mpostpassport.bmp', 'nothing', 1, '1', 0, '02456789', 1, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (16, 'Meditel', 'MED', 1, 1, 'meditel.png', 'p_meditel.bmp', '', 3, '1', 0, '121 ou le 06 63 121 121', 1, 4, 'comment recharger? 555....', 'D63738');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (17, 'Lydec', 'LD', 8, 1, 'lydec.png', 'p_lydec.bmp', NULL, 0, '1', 0, 'info@mpost.ma', 1, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (18, 'MPOST PASSPORT A', 'MPAC', 6, 1, 'mpostpassport.png', 'p_mpostpassport.bmp', 'nothing', 1, '1', 0, '02456789', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (19, 'Terminal Lease', 'TL', 1000, 1, 'terminallease.png', 'p_terminallease.bmp', 'nothing', 0, '1', 0, '0', 0, 0, 'nothing', 'D');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (20, '3G SIM', '3G', 1000, 1, '3g.png', 'P_3g.bmp', 'nothing', 0, '1', 0, 'nothing', 0, 1, 's', '45');
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (21, 'Maroc Telecom Fixe', 'MTF', 8, 1, 'maroctelecom.png', 'p_maroctelecom.bmp', NULL, 1, '1', 0, 'info@mpost.ma', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (23, 'MarocTelecom Mobile', 'MTB', 8, 1, 'maroctelecom.png', 'p_maroctelecom.bmp', NULL, 1, '1', 0, 'info@mpost.ma', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (25, 'Maroc Telecom Int', 'MTI', 8, 1, 'maroctelecom.png', 'p_maroctelecom.bmp', NULL, 1, '1', 0, 'info@mpost.ma', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (26, 'MPOST PASSPORT R', 'MPRE', 6, 1, 'mpostpassport.png', 'p_mpostpassport.bmp', 'nothing', 1, '1', 0, '02456789', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (27, 'lydec V2', 'LD', 8, 1, 'lydec.png', 'p_lydec.bmp', NULL, 0, '1', 0, 'info@mpost.ma', 0, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (28, 'Amendis V2', 'AM', 8, 1, 'amendis.png', 'p_amendis.bmp', NULL, 1, '1', 0, '0802008000', 1, 0, NULL, NULL);
INSERT INTO Product([nId], sName, sCode, nServiceId, bActive, [sLogo], sPrintLogo, sPrintText, nPosition, nCountryId, [bModify], sCustomerCare, bPass2Pay, nPass2PayPosition, sInfoText, sPass2PayBGCode) VALUES (30, 'Radeet', 'RT', 8, 1, 'radeet.png', 'p_radeet.bmp', NULL, 1, '1', 0, 'info@mpost.ma', 1, 1, NULL, NULL);

-- //@UNDO
-- SQL to undo the change goes here.


