-- // insert default product category
-- Migration SQL that makes the change goes here.

INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (1, 1, 1, 0, 1, 1, 1, 1, 0, 'Radeema Regie', 'radeema.png', '1111111111111', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (2, 2, 1, 0, 1, 1, 5, 4, 0, 'Bayn 5 DH', 'bayn5.png', '6111248683000', 1, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (3, 2, 1, 0, 1, 1, 10, 8, 0, 'Bayn 10 DH', 'bayn10.png', '6111248682997', 2, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (4, 2, 1, 0, 1, 1, 20, 16, 0, 'Bayn 20 DH', 'bayn20.png', '6111248682980', 3, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (5, 2, 1, 0, 1, 1, 50, 41, 0, 'Bayn 50 DH', 'bayn50.png', '6111248682973', 4, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (6, 2, 1, 0, 1, 1, 100, 83, 0, 'Bayn 100 DH', 'bayn100.png', '6111248682966', 5, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (7, 3, 1, 0, 1, 1, 10, 8, 0, 'INWI 10 DH', 'inwi10.png', '6111248682591', 1, 0, 20, 1, 1, 1, 1, 'lydec.cfm', NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (8, 3, 1, 0, 1, 1, 20, 16, 0, 'INWI 20 DH', 'inwi20.png', '6111248682607', 2, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (9, 3, 1, 0, 1, 1, 50, 41, 0, 'INWI 50 DH', 'inwi50.png', '6111248682621', 3, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (10, 3, 1, 0, 1, 1, 100, 83, 0, 'INWI 100 DH', 'inwi100.png', '6111248682645', 4, 0, 20, 1, 1, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (11, 5, 1, 0, 1, 1, 10, 8, 0, 'HDM 1J', 'wanahdm1j.png', '6111248682065', 1, 0, 20, 1, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (12, 5, 1, 0, 1, 1, 20, 16, 0, 'HDM 2J', 'wanahdm2j.png', '6111248681952', 2, 0, 20, 1, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (13, 5, 1, 0, 1, 1, 200, 166, 0, 'HDM 30J', 'wanahdm30j.png', '6111248681389', 3, 0, 20, 1, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (14, 7, 1, 0, 1, 1, 2, 2, 0, 'Redal Regie', 'redal.png', '2222222222222', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (15, 8, 1, 0, 1, 1, 1, 0, 0, 'Radeel', 'radeel.png', '3333333333333', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (16, 9, 1, 0, 1, 1, 10, 0, 0, 'Jawal 10 ', 'maroctelecom10.png', '1111111111111', 1, 0, 20, 1, 1, 0, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (17, 9, 1, 0, 1, 1, 50, 0, 0, 'Jawal 50', 'maroctelecom50.png', '2222222222222', 3, 0, 20, 1, 1, 0, 3, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (18, 9, 1, 0, 1, 1, 100, 0, 0, 'Jawal 100', 'maroctelecom100.png', '3333333333333', 4, 0, 20, 1, 1, 0, 4, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (19, 10, 1, 0, 1, 1, 1, 1, 0, 'Ramsa', 'ramsa.png', '4444444444444', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (20, 11, 1, 0, 1, 1, 2, 2, 0, 'Amendis', 'amendis.png', '6666666666666', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (21, 12, 1, 0, 1, 1, 1, 1, 0, 'TeleFlouss', 'teleflous.png', '777777777777', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (22, 13, 1, 0, 1, 1, 0, 0, 0, 'La Redoute', 'laredoute.png', '7777777777777', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (23, 14, 1, 0, 1, 1, 50, 0, 0, 'Mpost Passport 50', 'mpostpassport50.png', '7777777777777', 1, 0, 20, 0, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (24, 14, 1, 0, 1, 1, 100, 0, 0, 'Mpost Passport 100', 'mpostpassport100.png', '7777777777777', 1, 0, 20, 0, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (25, 14, 1, 0, 1, 1, 200, 0, 200, 'Mpost Passport 200', 'mpostpassport200.png', '7777777777777', 1, 0, 20, 0, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (26, 14, 1, 0, 1, 1, 500, 0, 500, 'Mpost Passport 500', 'mpostpassport500.png', '7777777777777', 1, 0, 20, 1, 1, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (27, 15, 1, 0, 1, 1, 0, 0, 0, 'likoul', 'cash2card1.png', '7777777777777', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (28, 15, 1, 0, 1, 1, 0, 0, 0, 'apay', 'cash2card2.png', '7777777777777', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (29, 16, 1, 1, 1, 1, 5, 0, 0, 'Meditel 5', 'meditel5.png', '8888888888888', 2, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (30, 16, 1, 1, 1, 1, 10, 0, 0, 'Meditel 10', 'meditel10.png', '9999999999999', 3, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (31, 16, 1, 1, 1, 1, 20, 0, 0, 'Meditel 20', 'meditel20.png', '6666666666666', 4, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (32, 16, 1, 1, 1, 1, 50, 0, 0, 'Meditel 50', 'meditel50.png', '5555555555555', 5, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (33, 16, 1, 1, 1, 1, 100, 0, 0, 'Meditel 100', 'meditel100.png', '4444444444444', 6, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (34, 17, 1, 0, 0, 1, 2, 0, 0, 'Lydec', 'lydec.png', '1111111111111', 1, 0, 0, 0, 0, 1, 1, 'lydec.cfm', 'Lydec_job.cfm');
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (35, 16, 1, 1, 1, 1, 1, 0, 0, 'Meditel 1', 'meditel1.png', '1111111111111', 1, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (36, 16, 1, 1, 1, 1, 200, 0, 0, 'Meditel 200', 'meditel200.png', '2222222222222', 7, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (37, 16, 1, 1, 1, 1, 500, 0, 0, 'Meditel 500', 'meditel500.png', '5005005005005', 8, 0, 10, 0, 0, 1, 1, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (39, 9, 1, 0, 1, 1, 20, 0, 0, 'Jawal 20', 'maroctelecom20.png', '2222222222222', 2, 0, 20, 1, 1, 1, 2, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (40, 19, 1, 0, 1, 1, 100, 0, 0, 'Terminal Lease', 'terminal-lease.png', '7070707070', 9, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (41, 20, 1, 0, 1, 1, 100, 0, 0, '3G SIM', '3g.png', '123456789', 2, 0, 1, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (42, 21, 1, 0, 1, 1, 2, 0, 0, 'Maroc Telecom Fixe', 'maroctelecom.png', '222222222222', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (43, 23, 1, 0, 1, 1, 2, 2, 0, 'Maroc Telecom Mobile', 'maroctelecom.png', '33333333333', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (44, 25, 1, 0, 1, 1, 2, 2, 0, 'Maroc Telecom Int', 'maroctelecom.png', '444444444444', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (46, 18, 1, 0, 1, 1, 0, 0, 0, 'MPOST PASSPORT ACTIVE', 'mpostpassport.png', '1122334455667', 1, 0, 0, 0, 0, 0, 0, 'rp_active_mpostpassport.cfm', 'task22/process.cfm');
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (47, 26, 1, 0, 1, 1, 0, 0, 0, 'MPOST PASSPORT eRELOAD', 'mpostpassport.png', '123456789456', 1, 0, 0, 0, 0, 0, 0, 'rp_ereload_mpostpassport.cfm', 'task23/process.cfm');
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (48, 27, 1, 0, 0, 1, 2, 0, 0, 'Lydec', 'lydec.png', '1111111111111', 1, 0, 0, 0, 0, 0, 1, 'lydecV2.cfm', 'lydecv2_job.cfm');
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (49, 28, 1, 0, 1, 1, 2, 2, 0, 'Amendis V2', 'amendis.png', '6666666666666', 1, 0, 0, 0, 0, 0, 0, 'rp_amendisV2.cfm', 'amendisV2_jpb.cfm');
INSERT INTO ProductCategory(nId, nProductId, bActive, bCustomized, bRegular, nPeriodId, nValue, nValueExVat, nVat, sName, sLogo, nCodeBar, nPosition, bModify, nStockAlert, bAlert, bStockManagement, bPass2Pay, nPass2PayPosition, sReprintProcess, sJob) VALUES (50, 30, 1, 0, 1, 1, 1, 1, 0, 'Radeet Regie', 'radeet.png', '1111111111111', 1, 0, 0, 0, 0, 0, 0, NULL, NULL);

-- //@UNDO
-- SQL to undo the change goes here.


